Resources:
  WebsocektSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: websocket-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: topic
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
        - AttributeName: topic
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: topic
          KeySchema:
            - AttributeName: topic
              KeyType: HASH
          Projection:
            ProjectionType: ALL
