service: aurora-sls-test

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:PROFILE, 'default'}
  region: ${env:REGION, 'eu-west-1'}
  stage: ${env:ENV, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds:*
        - secretsmanager:*
      Resource: "*" # Open permissions for example sake
  environment:
    RDS_DB_CLUSTER_ARN: !GetAtt AuroraDBCluster.DBClusterArn
    RDS_DB_SECRET_ARN: SECRETS_MANAGER_RDS_DB_SECRET

plugins:
  - serverless-esbuild

functions:
  - ${file(./serverless/functions.yml)}

resources:
    - ${file(./serverless/vpc.yml)}
    - ${file(./serverless/rds.yml)}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20